#!/usr/bin/env runhaskell

-- vim: set filetype=haskell :

module NewPost.Main where

import System.Environment   (getArgs) 
import System.IO            (IOMode(..), hPutStrLn, withFile)

import NewPost

-- | This is a very basic program that accepts a single argument (post title)
-- and creates a new post file with the appropriate name and header 
-- information.
main :: IO ()
main = do
    args <- getArgs
    date <- today
    let rawTitle = concat args
        fileName = newPostFileName date rawTitle
    withFile fileName WriteMode $ \handle ->
        hPutStrLn handle $ header date rawTitle
